/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,tsx,ts}', './src/*.{html,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c7c4d8',
        'on-tertiary-fixed': '#00201d',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#3323cc',
        'surface-variant': '#2d3449',
        'inverse-on-surface': '#283044',
        'surface-bright': '#31394d',
        'on-primary-container': '#dad7ff',
        'surface-container-highest': '#2d3449',
        'error': '#ffb4ab',
        'primary-container': '#4f46e5',
        'surface-tint': '#c3c0ff',
        'primary': '#c3c0ff',
        'background': '#0b1326',
        'inverse-primary': '#4d44e3',
        'error-container': '#93000a',
        'secondary': '#d2bbff',
        'tertiary-fixed': '#89f5e7',
        'on-tertiary': '#003732',
        'on-secondary-container': '#c9aeff',
        'surface-container-lowest': '#060e20',
        'secondary-fixed-dim': '#d2bbff',
        'tertiary-container': '#006c63',
        'tertiary': '#6bd8cb',
        'on-error': '#690005',
        'on-secondary': '#3f008e',
        'inverse-surface': '#dae2fd',
        'primary-fixed': '#e2dfff',
        'on-primary': '#1d00a5',
        'outline-variant': '#464555',
        'surface-container-low': '#131b2e',
        'surface': '#0b1326',
        'primary-fixed-dim': '#c3c0ff',
        'secondary-fixed': '#eaddff',
        'on-secondary-fixed': '#25005a',
        'on-background': '#dae2fd',
        'on-secondary-fixed-variant': '#5a00c6',
        'on-tertiary-fixed-variant': '#005049',
        'surface-container': '#171f33',
        'on-tertiary-container': '#81eddf',
        'surface-dim': '#0b1326',
        'outline': '#918fa1',
        'surface-container-high': '#222a3d',
        'on-primary-fixed': '#0f0069',
        'secondary-container': '#6001d1',
        'tertiary-fixed-dim': '#6bd8cb',
        accent: {
          violet: '#8b5cf6',
          amber: '#f59e0b',
          rose: '#f43f5e',
          emerald: '#10b981',
          cyan: '#06b6d4',
        },
      },
      fontFamily: {
        'display-lg': ['Playfair Display', 'Georgia', 'serif'],
        'headline-md': ['Playfair Display', 'Georgia', 'serif'],
        'body-lg': ['Manrope', 'system-ui', 'sans-serif'],
        'body-md': ['Manrope', '"Microsoft YaHei"', 'system-ui', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'Consolas', 'monospace'],
        display: ['Playfair Display', 'Georgia', 'serif'],
        body: ['Manrope', '"Microsoft YaHei"', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Consolas', 'monospace'],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-out-right': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'pop': {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.12)' },
          '100%': { transform: 'scale(1)' },
        },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-2px)' },
          '75%': { transform: 'translateX(2px)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'progress-shrink': {
          '0%': { transform: 'scaleX(1)' },
          '100%': { transform: 'scaleX(0)' },
        },
        'breathing': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out forwards',
        'fade-in-up': 'fade-in-up 0.4s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.25s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'slide-out-right': 'slide-out-right 0.2s ease-in forwards',
        'slide-up': 'slide-up 0.3s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'scale-in': 'scale-in 0.25s ease-out forwards',
        'pop': 'pop 0.3s ease-out',
        'shake': 'shake 0.3s ease-in-out',
        'shimmer': 'shimmer 1.5s linear infinite',
        'progress-shrink': 'progress-shrink 3s linear forwards',
        'breathing': 'breathing 2s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
      },
      transitionTimingFunction: {
        'bounce-sm': 'cubic-bezier(0.34,1.56,0.64,1)',
      },
      borderWidth: {
        '1': '1px',
      },
      zIndex: {
        'overlay': 1000,
        'modal': 2000,
        'toast': 3000,
        'max': 9999,
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        'sidebar-width': '280px',
        'unit': '8px',
        'gutter': '32px',
      },
      boxShadow: {
        'premium': '0 10px 30px -10px rgba(0, 0, 0, 0.5)',
        'premium-hover': '0 20px 40px -15px rgba(0, 0, 0, 0.6)',
        'ambient': '0 0 60px -10px rgba(195, 192, 255, 0.1)',
        'glow': '0 0 30px -5px rgba(195, 192, 255, 0.15)',
      },
    },
  },
  plugins: [],
};
